MODULE_OP_READ_SEMP_VERSION = 'read_semp_version'
MODULE_OP_READ_OBJECT_LIST = 'read_object_list'
MODULE_OP_READ_OBJECT = 'read_object'
MODULE_OP_CREATE_OBJECT = 'create_object'
MODULE_OP_DELETE_OBJECT = 'delete_object'
MODULE_OP_UPDATE_OBJECT = 'update_object'
